Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.

Resources:
  S3StaticBucket:
    Metadata:
      'aws:copilot:description': 'An Amazon S3 bucket to store and retrieve objects for static files.'
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        'Fn::Transform':
           Name: 'String'
           Parameters:
             InputString: !Sub '${AWS::StackName}-static'
             Operation: Lower
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - '*'
            MaxAge: 3600

  S3StaticBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource:
              - !Sub ${ S3StaticBucket.Arn}/*
              - !Sub ${ S3StaticBucket.Arn}
          - Sid: ForceHTTPS
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub ${ S3StaticBucket.Arn}/*
              - !Sub ${ S3StaticBucket.Arn}
            Condition:
              Bool:
                "aws:SecureTransport": false
      Bucket: !Ref S3StaticBucket

  S3StaticAccessPolicy:
    Metadata:
      'aws:copilot:description': 'An IAM ManagedPolicy for your service to access the static bucket'
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Sub
        - Grants CRUD access to the S3 bucket ${Bucket}
        - { Bucket: !Ref S3StaticBucket }
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: S3ObjectActions
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:PutObjectACL
              - s3:PutObjectTagging
              - s3:DeleteObject
              - s3:RestoreObject
            Resource: !Sub ${ S3StaticBucket.Arn}/*
          - Sid: S3ListAction
            Effect: Allow
            Action: s3:ListBucket
            Resource: !Sub ${ S3StaticBucket.Arn}

Outputs:
  AwsStorageBucketNameStatic:  # This will be injected as AWS_STORAGE_BUCKET_NAME_STATIC
    Description: "The name of a deep static bucket."
    Value: !Ref S3StaticBucket
    Export:
      Name: !Sub ${App}-${Env}-StaticBucket

  S3StaticAccessPolicy:
    Description: "The IAM::ManagedPolicy to attach to the task role"
    Value: !Ref S3StaticAccessPolicy
    Export:
      Name: !Sub ${App}-${Env}-S3StaticAccessPolicy
