# The manifest for the "pipeline-deep-deeper" pipeline.
# This YAML file defines your pipeline: the source repository it tracks and the order of the environments to deploy to.
# For more info: https://aws.github.io/copilot-cli/docs/manifest/pipeline/

# The name of the pipeline.
name: pipeline-deep-deeper

# The version of the schema used in this template.
version: 1

# This section defines your source, changes to which trigger your pipeline.
source:
  # The name of the provider that is used to store the source artifacts.
  # (i.e. GitHub, Bitbucket, CodeCommit)
  provider: GitHub
  # Additional properties that further specify the location of the artifacts.
  properties:
    branch: main
    repository: https://github.com/the-deep/deeper
    # Optional: specify the name of an existing CodeStar Connections connection.
    # connection_name: a-connection

# This section defines the order of the environments your pipeline will deploy to.
stages:
    - name: staging  # The name of the environment.
      requires_approval: true
      # Optional: flag for manual approval action before deployment.
      # Optional: use test commands to validate this stage of your build.
      test_commands:
        # Use this to run migration until we can do post deployment hooks from copilot
        # https://github.com/aws/copilot-cli/issues/3007
        - yum update -y && yum install -y sudo
        - wget -q https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v1.13.0
        - mv ./copilot-linux-v1.13.0 ./copilot-linux
        - chmod +x ./copilot-linux
        - echo 'Running collectstatic'
        - unbuffer ./copilot-linux svc exec -c "python3 manage.py collectstatic --no-input" -n web -e staging --yes
        - echo 'Running migrations'
        - unbuffer ./copilot-linux svc exec -c "python3 manage.py migrate --no-input" -n web -e staging --yes

    - name: prod  # The name of the environment.
      requires_approval: true
      # Optional: flag for manual approval action before deployment.
      # Optional: use test commands to validate this stage of your build.
      test_commands:
        # Use this to run migration until we can do post deployment hooks from copilot
        # https://github.com/aws/copilot-cli/issues/3007
        - yum update -y && yum install -y sudo
        - wget -q https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v1.13.0
        - mv ./copilot-linux-v1.13.0 ./copilot-linux
        - chmod +x ./copilot-linux
        - echo 'Running collectstatic'
        - unbuffer ./copilot-linux svc exec -c "python3 manage.py collectstatic --no-input" -n web -e prod --yes
        - echo 'Running migrations'
        - unbuffer ./copilot-linux svc exec -c "python3 manage.py migrate --no-input" -n web -e prod --yes
